name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'GraphMailer.Email.sln'

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: make restore and build
      run: make build


        #    - name: Publish
        #run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
    - name: Version and Tag
      id: bump_version
      uses: mathieudutour/github-tag-action@v5.2
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          
    - name: Pack
      run: cd GraphMailer/GraphMailer/GraphMailer.Email.Sender ;dotnet pack -o . --no-build --no-restore -c Release -p:PackageVersion=${{ steps.bump_version.outputs.new_tag }}
        
    - name: Push
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} --skip-duplicate
        #run: dotnet nuget push ./output/*.nupkg --skip-duplicate -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
