name: Publish Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: PWD
      run: pwd
    - name: Install dependencies
      run: dotnet restore
    - name: change dir
      run: cd /home/runner/work/GraphMailer/GraphMailer/GraphMailer.Email
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish GraphMailer.Email
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: GraphMailer.Email/FluentEmail.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
